version: "3.9"
name: "money_transfer"

services:
  postgres:
    image: postgres:15
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - ../config/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
    restart: unless-stopped
    networks:
      money_transfer:

  migration:
    build:
      context: ../.
      dockerfile: ./deployments/migrations/Dockerfile
    env_file:
      - ../config/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      money_transfer:

  app:
    build:
      context: ../.
      dockerfile: ./deployments/app/Dockerfile
    env_file:
      - ../config/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migration
    networks:
      money_transfer:

volumes:
  pg-data:

networks:
  money_transfer:
    name: "money_transfer_network"