http_server:
  port: "8080"
  read_timeout: "3s"
  write_timeout: "3s"
  shutdown_timeout: "2s"

zap_logger:
  level: "info"
  encoding: "json"
  output_path: ["stdout"]
  error_output_path: ["stdout"]

postgres:
  max_pool_size: 20
  conn_timeout: "1s"
  conn_attempts: 5
